Extend definition file
kiegroup/build-chain-configuration-reader pull request #59
Opened 2022-11-03 22:09 UTC by shubhbapna

Resolves #57

2022-11-04 07:28 UTC, Ginxo requested changes
I don't see the test case where the definition-file extends and dependencies are externalized on a file, could you please add? Thanks

2022-11-04 12:57 UTC, shubhbapna commented
> I don't see the test case where the definition-file extends and dependencies are externalized on a file, could you please add? Thanks

You mean testing something like this?
```yaml
version: "2.2"

extends: ./build-config.yaml

dependencies: ./project-dependencies.yaml

default:
  build-command:
    current: echo overriden

build:
  - project: kiegroup/appformer
    build-command:
      upstream: echo changed
```

2022-11-07 07:29 UTC, Ginxo commented
> > I don't see the test case where the definition-file extends and dependencies are externalized on a file, could you please add? Thanks
> 
> You mean testing something like this?
> 
> ```yaml
> version: "2.2"
> 
> extends: ./build-config.yaml
> 
> dependencies: ./project-dependencies.yaml
> 
> default:
>   build-command:
>     current: echo overriden
> 
> build:
>   - project: kiegroup/appformer
>     build-command:
>       upstream: echo changed
> ```

that's it

2022-11-07 07:35 UTC, Ginxo requested changes
@shubhbapna LGTM just few test cases are missing

2022-11-07 16:27 UTC, lampajr approved these changes

2022-11-08 12:55 UTC, Ginxo approved these changes
LGTM

2022-11-08 12:55 UTC, Ginxo commented
this needs backporting to typescript/main

2022-11-08 12:58 UTC, merged